name: Build & Deploy to Firebase

on:
  workflow_dispatch:
    inputs:
      flavor:
        description: 'Select flavor to build'
        required: true
        default: 'free'
        type: choice
        options:
          - free
          - pro
      buildType:
        description: 'Select build type'
        required: true
        default: 'release'
        type: choice
        options:
          - debug
          - release

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up JDK
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '17'

      - name: Grant execute permission for gradlew
        run: chmod +x gradlew

      - name: Build selected flavor
        run: ./gradlew assemble${{ github.event.inputs.flavor | capitalize }}${{ github.event.inputs.buildType | capitalize }}

      - name: Upload to Firebase App Distribution
        uses: wzieba/Firebase-Distribution-Github-Action@v1
        with:
          appId: ${{ secrets.FIREBASE_APP_ID_${{ github.event.inputs.flavor | upper }} }}
          token: ${{ secrets.FIREBASE_TOKEN }}
          groups: testers
          file: app/build/outputs/apk/${{ github.event.inputs.flavor }}/${{ github.event.inputs.buildType }}/app-${{ github.event.inputs.flavor }}-${{ github.event.inputs.buildType }}.apk
